# Generated by Django 2.0.5 on 2019-05-13 15:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', tinymce.models.HTMLField(blank=True, max_length=4096, verbose_name='Codigo')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
