# Generated by Django 2.0.5 on 2019-05-13 15:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={'verbose_name_plural': 'Lista de código compartido'},
        ),
        migrations.AlterField(
            model_name='codigo',
            name='codigo',
            field=tinymce.models.HTMLField(blank=True, max_length=16384, verbose_name='Código'),
        ),
    ]
