# Generated by Django 2.0.5 on 2019-05-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0002_auto_20190513_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
