# Generated by Django 2.0 on 2019-05-13 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0003_auto_20190513_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(blank=True, max_length=128, verbose_name='Descripción')),
                ('tiempo', models.IntegerField(blank=True, verbose_name='Tiempo de Expiración')),
                ('unidad', models.CharField(choices=[('0', 'Nunca'), ('1', 'Horas'), ('2', 'Días'), ('3', 'Semanas'), ('4', 'Meses')], max_length=1)),
                ('activo', models.BooleanField(max_length=128, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Tiempo de Duración',
            },
        ),
        migrations.AddField(
            model_name='codigo',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='codigo',
            name='expiracion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codigo.Duracion'),
            preserve_default=False,
        ),
    ]
